import estedad from "@/constants/LocalFont";
import "./globals.css";
import Providers from "./Provider";
import Layout from "@/container/Layout";
import { Toaster } from "react-hot-toast";
import ReduxProvider from "@/redux/Provider";

export const metadata = {
  title: "Tarkhine",
  description: "Generated by Alidev_r1996",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <head>
        <link
          rel="shortcut icon"
          href="data:;base64,iVBORw0KGgo="
          type="image/x-icon"
        />
      </head>
      <body className={`${estedad.variable} font-sans`}>
        <Providers>
          <Toaster />
          <ReduxProvider>
            <Layout>{children}</Layout>
          </ReduxProvider>
        </Providers>
      </body>
    </html>
  );
}
